name: Send Message on Teams
on: push
jobs:
    deployment:
        runs-on: ubuntu-latest
        steps:
        - name: Post commit message to Teams channel
          uses: satak/webrequest-action@master
          with:
              url: ${{ secrets.TEAMS_WEBHOOK }}
              method: POST
              payload: '{"text": "New Commit on master by ${{ github.actor }}"} of https://github.com/bishrant/MapMyProperty. Make sure you download the latest version.'
