name: Send Message on Teams
on:
    push:
        branches-ignore:
            - '**'

jobs:
    deployment:
        runs-on: ubuntu-latest
        steps:
        - name: Post commit message to Teams channel
          uses: satak/webrequest-action@master
          with:
              url: ${{ secrets.TEAMS_WEBHOOK }}
              method: POST
              payload: '{"text": "New commit on master by ${{ github.actor }} for github repo https://github.com/bishrant/MapMyProperty. Make sure you download the latest version."}'
